import { twMerge } from "tailwind-merge";
const buttonTextStyles = [
  "text-base",
  "font-gluten",
  "font-bold",
  "text-white",
  "text-center",
  "relative tracking-[0.03em] leading-[16px]",
];

export const primaryStyles = twMerge(
  "w-full",
  "relative",
  "rounded-[54px]",
  "bg-base-colors/brand-600",
  "flex",
  "flex-row",
  "items-center",
  "justify-center",
  "h-12",
  "box-border",
  "pt-2.5",
  "px-4",
  "pb-2",
  buttonTextStyles,
  "hover:bg-base-colors/brand-400",
  "active:bg-base-colors/brand-700",
  "aria-pressed:bg-base-colors/brand-700",
  "aria-[disabled=true]:opacity-50",
  "aria-[disabled=true]:text-opacity-50",
  "aria-[disabled=true]:cursor-not-allowed",
  "aria-[disabled=true]:pointer-events-none",
);

export const secondaryStyles = twMerge(
  "w-full relative",
  "rounded-[54px] box-border h-12",
  "flex flex-row items-center justify-between",
  "pt-2.5 px-4 pb-2",
  "border-t-[1px] border-solid border-r-[1px] border-b-[3px] border-l-[1px]",
  "border-base-colors/brand-600",
  buttonTextStyles,
  "text-base-colors/brand-600",
  "hover:border-base-colors/brand-400",
  "hover:text-base-colors/brand-400",
  "active:border-base-colors/brand-700",
  "active:text-base-colors/brand-700",
  "aria-disabled:text-opacity-40",
  "aria-disabled:border-opacity-40",
  "aria-disabled:pointer-events-none",
  "text-center",
  "items-center",
  "justify-center",
);
