name: 🚀 Dev Ops
description: Submit a Dev Ops change request
labels: ["DevOps"]
body:
  - type: textarea
    attributes:
      label: Description
      description: What is the problem or desired behavior for the CI/CD / Developer tools?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: Please outline the motivation for the proposal and why it should be implemented.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Change
      description: Please outline the change for the proposal in detail.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Additional Information
      description: Please select all conditions that apply.
      options:
        - label: It is related to the Storybook?
        - label: It is related to the GitHub Actions?
        - label: It is related to the developer tools?

